### ISSUE TITLE
Blizzard_APIDocumentationGenerated error by missing a `}`

### ISSUE THREAD

**Issue by EKE00372** [Stanzilla/WoWUIBugs#629] opened 2024-08-15 04:31 UTC
`ddOns/Blizzard_APIDocumentationGenerated/PetConstantsDocumentation.lua:14: '}' expected near 'MAX_SUMMONABLE_HUNTER_PETS'`

Error can trigger by WA's API search function

**Comment by Nevcairiel** [comment] 2024-08-15 05:04
Duplicate of #626

**Closed as not planned** 2024-08-15 05:05 UTC
