### ISSUE TITLE
TBC: Fonts in Non-Latin languages client incorrect

### ISSUE THREAD

**Issue by EKE00372** [Stanzilla/WoWUIBugs#76] opened 2021-04-01 23:14 UTC
For Non-Latin languages locale client (koKR/zhTW/zhCN/ruRU), ~`STANDARD_TEXT_FONT` should be "Fonts\\blei00d.TTF" but it's "Fonts\\FRIZQT__.TTF" now.~ `STANDARD_TEXT_FONT`, `UNIT_NAME_FONT` and `DAMAGE_TEXT_FONT` are all be "Fonts\\FRIZQT__.TTF"  now.

![$7P~N% LF5Z{6NGQ}%MKTMP](https://user-images.githubusercontent.com/1412472/113363038-67b6d900-9382-11eb-9f3b-891a96660dfe.png)

**Comment by EKE00372** [comment] 2021-04-03 15:41
I just notice that not only happened on zhTW client

**Comment by CyanoHao** [comment] 2021-04-04 00:04
Root cause:

In [FrameXML.toc](https://github.com/tomrus88/BlizzardInterfaceCode/blob/ace1af63e38c058fa76cd3abca0b57b384c527d4/Interface/FrameXML/FrameXML.toc), `Fonts.xml` (line 7) is placed before `Localization.xml` (line 53).

Therefore, in the `<Script>` block in [Fonts.xml](https://github.com/tomrus88/BlizzardInterfaceCode/blob/4334b87a5365523a8d5211fba0819818946a967f/Interface/FrameXML/Fonts.xml), none of `LOCALE_**` variables are initialized in non-Latin languages, and the `else` branch is always chosen.

**Comment by Meorawr** [comment] 2021-04-12 22:44
Fixed in 2.5.1.38285.

**Closed by Meorawr** 2021-04-12 22:44 UTC
Labels: Acknowledged by Blizzard, Bug, TBC
