### ISSUE TITLE
Interact key causes ADDON_ACTION_FORBIDDEN on unprotected function calls

### ISSUE THREAD

**Issue by seblindfors** [Stanzilla/WoWUIBugs#319] opened 2022-10-27 10:01 UTC
How to reproduce:
1) Find an NPC offering gossip or a quest.
2) Use interact key (`INTERACTTARGET`) to start the dialogue.
3) Run either of the following depending on type of dialogue:
```
/run C_GossipInfo.CloseGossip()
/run CloseQuest()
```
Results in:
```*** ForceTaint_Strong ***' tried to call the protected function 'CloseGossip()'.```

This is likely because the interact key is setting the NPC as an implicit target, and calling these unprotected functions will result in attempting to clear target from insecure code. Clearing the target before attempting to exit the interaction does not cause the same issue, neither does targeting the NPC preemptively before starting the interaction with the binding. The bug only affects creatures, game objects do not have implicit targeting so they are unaffected. 

Suggested solutions:
- Add insecure clear target internally in these functions, if `UnitIsUnit('target', 'npc')`
- Stop interact key from actually setting target on interactions, as it's not necessary to have the NPC targeted for an interaction to proceed.

**Comment by semlar** [comment] 2022-10-27 22:19
This error is also triggered when calling `CloseTaxiMap()` while interacting with a flight master using the interact key.

**Comment by Meorawr** [comment] 2022-11-03 21:01
This _may_ be fixed in the new 10.0.0.46455 PTR build; will need someone to test.

**Comment by seblindfors** [comment] 2022-11-04 16:00
Confirmed fixed on 10.0.0.46455

**Comment by Meorawr** [comment] 2023-09-21 00:43
Issue has reappeared as of I'd assume 10.1.7.51421 - possibly a consequence of the ClearTarget protection fixes.

**Comment by Voopie** [comment] 2024-02-29 14:26
I can't reproduce it in 10.2.5.53441
Seems to be fixed

**Closed as completed** 2024-03-01 01:12 UTC
Labels: Bug, Mainline, ✔️ Verifiable Example
