### ISSUE TITLE
Expected talentIndex arg for GetTalentInfo differs in Wrath Classic Beta to that from Classic/TBC Classic

### ISSUE THREAD

**Issue by EsreverWoW** [Stanzilla/WoWUIBugs#244] opened 2022-07-15 17:50 UTC
Presently on the Wrath Classic Beta (build 44644), GetTalentInfo is seemingly returning incorrect info when passing arguments like one would expect coming from Classic/TBC Classic.

As an example, we can use a Paladin's Blessing of Sanctuary talent.

In Classic, you might use `GetTalentInfo(2, 12)` to obtain information on this talent since it is in the second tree and is the 12th talent in that tree.
![image](https://user-images.githubusercontent.com/49285632/179281503-b1b4babb-daf2-4b93-ad3f-292ed23a0767.png)

In TBC Classic, you would use `GetTalentInfo(2, 14)` since this talent moves to the 14th position in this version of the game.
![image](https://user-images.githubusercontent.com/49285632/179281899-11aac20f-aaee-4639-b94a-a6ae555c0b7f.png)

Now, in Wrath Classic, you might expect `GetTalentInfo(2, 12)` to provide information on Blessing of Sanctuary, but instead you must use `GetTalentInfo(2, 8)`.

**Comment by EsreverWoW** [comment] 2022-07-15 18:06
```lua
/run local f, name=nil, GetSpellInfo(20911) if name then for i=1,3 do for j=1,99 do local n=GetTalentInfo(i,j) if n==name then f=true print("Tree/Index: "..i..", "..j) break elseif i==3 and j==99 and not f then print("Not Found!") end end end end
```
This should print out the tree/index of a given spellID, in this case 20911 for Blessing of Sanctuary, should one be found.

**Comment by mrbuds** [comment] 2022-08-12 10:23
I don't think it's a bug, old talents keep same index, new talents gets new ones.
`GetTalentInfo(2, 12)` gives tier & column as 3rd & 4th returns (5 & 2 in your example).

**Comment by Meorawr** [comment] 2022-08-12 10:44
I'm also leaning strongly to this not being a bug. I've updated the wiki to remove the assumption that talent indices mapped to display positions in trees.

**Comment by Ketho** [comment] 2022-08-12 14:13
I suppose all of the confusion is because I just documented it wrong by making that assumption 🙈

**Comment by EsreverWoW** [comment] 2022-08-16 03:17
I should note that behavior on Wrath Classic at present differs from that of the original 3.3.5a client. Using Improved Blessing of Might as an example, this is the output of `/dump GetTalentInfo(3, 5)` between the two.

3.3.5a (12340)
![image](https://user-images.githubusercontent.com/49285632/184790760-d251586a-23dd-42c6-b401-ec3cbb965a82.png)

3.4.0 (45043)
![image](https://user-images.githubusercontent.com/49285632/184790805-8531b690-6f36-4445-93e3-3c4694f6ac0a.png)

**Comment by Meorawr** [comment] 2022-08-16 07:30
Is there a specific problem this difference causes that can't be resolved by just doing a one-time loop over the talents and mapping them to display indices yourself with the position returns?

**Comment by Meorawr** [comment] 2023-05-16 20:05
Given that there's not been any movement on this and multiple people are of the mind it's not a bug I'll close this as probably intended (or rather - if it were a bug fixing it now would actually be _more_ harmful).

**Closed by Meorawr** 2023-05-16 20:05 UTC
Labels: Classic
