### ISSUE TITLE
TBC: FrameXML\RestrictedExecution.lua:473: Cannot call restricted closure from insecure code

### ISSUE THREAD

**Issue by siweia** [Stanzilla/WoWUIBugs#80] opened 2021-04-03 20:28 UTC
`frame:Execute([[
		buttons = table.new()
		for i = 1, 12 do
			tinsert(buttons, self:GetFrameRef("ActionButton"..i))
		end
	]])`

This error popups out when you have actionbar code written as above.

**Comment by Meorawr** [comment] 2021-04-03 20:29
Closing as duplicate of #66.

**Closed by Meorawr** 2021-04-03 20:29 UTC
