### ISSUE TITLE
WorldMapFrame.pinPools / MapCanvasDataProviderMixin taints guild control UI

### ISSUE THREAD

**Issue by AeroScripts** [Stanzilla/WoWUIBugs#114] opened 2021-04-29 05:22 UTC
This has been an issue in classic as far back as July 2020.

In both classic and TBC beta, the guild control UI is tainted by anything that uses WorldMapFrame.pinPools and MapCanvasDataProviderMixin. I have created a minimal example and steps to reproduce the issue. Working backwards after first discovering the bug with HereBeDragons, I came up with this very small piece of code to reproduce the issue:
```Lua
WorldMapFrame.pinPools["TaintTestTemplate"] = CreateFramePool("FRAME")
WorldMapFrame:AddDataProvider(CreateFromMixins(MapCanvasDataProviderMixin))
```

To reproduce: Enable only TaintTest, open the world map then close it. Then open the guild control UI and switch to a different guild rank. That will trigger an error like this:
![](https://cdn.discordapp.com/attachments/828347848570830858/837156383484805128/unknown.png)

Some interesting parts of taint.log
```
4/29 00:59:08.915  Execution tainted by TaintTest while reading textureWidth - Interface\AddOns\Blizzard_SharedMapDataProviders\MapExplorationDataProvider.lua:100 <unnamed>:RefreshOverlays()
4/29 00:59:08.915      Interface\AddOns\Blizzard_SharedMapDataProviders\MapExplorationDataProvider.lua:40 RefreshAllData()
4/29 00:59:08.915      Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:420 WorldMapFrame:RefreshAllDataProviders()
4/29 00:59:08.915      Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:448 WorldMapFrame:RefreshAll()
4/29 00:59:08.915      Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:61 OnShow()
4/29 00:59:08.915      Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:145
4/29 00:59:08.915      WorldMapFrame:Show()
4/29 00:59:08.915      Interface\FrameXML\UIParent.lua:2079 <unnamed>:SetUIPanel()
4/29 00:59:08.915      Interface\FrameXML\UIParent.lua:1924 <unnamed>:ShowUIPanel()
4/29 00:59:08.915      Interface\FrameXML\UIParent.lua:1785
4/29 00:59:08.915      <unnamed>:SetAttribute()
4/29 00:59:08.915      Interface\FrameXML\UIParent.lua:2531 ShowUIPanel()
4/29 00:59:08.915      Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:8 WorldMapFrame:HandleUserActionToggleSelf()
4/29 00:59:08.915      Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:182 ToggleWorldMap()
4/29 00:59:08.915      TOGGLEWORLDMAP:1
```
```
4/29 00:59:08.910  Global variable left tainted by TaintTest - 
4/29 00:59:08.910      GetExploredMapTextures()
4/29 00:59:08.910      Interface\AddOns\Blizzard_SharedMapDataProviders\MapExplorationDataProvider.lua:91 <unnamed>:RefreshOverlays()
4/29 00:59:08.910      Interface\AddOns\Blizzard_SharedMapDataProviders\MapExplorationDataProvider.lua:40 RefreshAllData()
4/29 00:59:08.910      Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:420 WorldMapFrame:RefreshAllDataProviders()
4/29 00:59:08.910      Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:448 WorldMapFrame:RefreshAll()
4/29 00:59:08.910      Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:61 OnShow()
4/29 00:59:08.910      Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:145
4/29 00:59:08.910      WorldMapFrame:Show()
4/29 00:59:08.910      Interface\FrameXML\UIParent.lua:2079 <unnamed>:SetUIPanel()
4/29 00:59:08.910      Interface\FrameXML\UIParent.lua:1924 <unnamed>:ShowUIPanel()
4/29 00:59:08.910      Interface\FrameXML\UIParent.lua:1785
4/29 00:59:08.910      <unnamed>:SetAttribute()
4/29 00:59:08.910      Interface\FrameXML\UIParent.lua:2531 ShowUIPanel()
4/29 00:59:08.910      Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:8 WorldMapFrame:HandleUserActionToggleSelf()
4/29 00:59:08.910      Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:182 ToggleWorldMap()
4/29 00:59:08.910      TOGGLEWORLDMAP:1
```
[Full taint.log from TBC beta](https://cdn.discordapp.com/attachments/829145713090625556/837195044221747270/taint.log)

**Comment by Meorawr** [comment] 2021-04-29 08:05
Map data provider/pin pool taint is _possibly_ also related to quest item buttons as there's a path to the objective tracker in retail when clicking on quests.

**Comment by kemayo** [comment] 2021-04-29 15:28
It *definitely* taints the route to the Encounter Journal from the map as well. (Easy to demonstrate: use any addon which has a custom map provider and try to click on a dungeon-boss icon during combat.)

**Comment by mkarer** [comment] 2021-05-10 05:36
Sounds like the issue I'm having since BfA: https://www.wowinterface.com/forums/showthread.php?t=57941

**Comment by Meorawr** [comment] 2021-09-15 22:38
For retail, map taint should be considerably reduced - and possibly completely resolved - as of 9.1.5.40196.

**Comment by Muehe** [comment] 2023-01-22 08:46
[As mentioned over here](https://github.com/Questie/Questie/issues/4424#issuecomment-1399414511) I just re-tested this on WoW 3.4.1 with Questie 7.4.8 and sadly we still have the taint issue. I assume the fixes are still not backported yet?

In case it helps there is an extensive taint.log added to the linked issue.

My method of reproduction is:

1. Disable `Modules\WorldMapTaintWorkaround.lua` in Questie's TOC.
2. Open guild management menu.
3. Select different role in the drop-down menu.

**Comment by Meorawr** [comment] 2023-01-22 12:39
It hasn't been backported yet, no.

**Comment by shooter-z** [comment] 2023-09-19 12:07
One thing I noticed while working on likely offshot of this bug on classic-era (taint of raid frames via UIDROPDOWNMENU_MENU_LEVEL) is that delaying AddDataProvider not to be run inline on file load, but during OnInitialize or after player_enter_world seems to resolve the issue. 
Don't have guild to test it, but I had reliable taints in raids traced down to providers that went out after that change.

**Comment by Meorawr** [comment] 2024-08-31 16:31
As Classic is finally getting new menus I'll close this. Should no longer be the case that the world map dropdowns can taint the guild control panel.

**Closed by Meorawr** 2024-08-31 16:31 UTC
Labels: Bug, Classic
